# Generated by Django 5.0.6 on 2026-05-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='напр. 2025-2026', max_length=20, unique=True, verbose_name='Навчальний рік')),
                ('start_date', models.DateField(verbose_name='Початок')),
                ('end_date', models.DateField(verbose_name='Кінець')),
                ('is_current', models.BooleanField(default=False, verbose_name='Поточний')),
            ],
            options={
                'verbose_name': 'Навчальний рік',
                'verbose_name_plural': 'Навчальні роки',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Назва предмету')),
                ('short_code', models.CharField(blank=True, max_length=8, verbose_name='Скорочення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.PositiveSmallIntegerField(help_text='1..11', verbose_name='Паралель')),
                ('letter', models.CharField(default='А', max_length=2, verbose_name='Літера')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='school_core.academicyear', verbose_name='Навчальний рік')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='accounts.teacherprofile', verbose_name='Класний керівник')),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Класи',
                'ordering': ['grade_level', 'letter'],
                'unique_together': {('grade_level', 'letter', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('period_number', models.PositiveSmallIntegerField(default=1, help_text='Порядковий номер уроку в розкладі', verbose_name='№ уроку')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема уроку')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнє завдання')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='accounts.teacherprofile')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school_core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='school_core.subject')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-date', 'period_number'],
                'indexes': [models.Index(fields=['school_class', 'date'], name='school_core_school__a1d554_idx'), models.Index(fields=['teacher', 'date'], name='school_core_teacher_1deb0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='school_core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='school_core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Призначення вчителя',
                'verbose_name_plural': 'Призначення вчителів',
                'unique_together': {('teacher', 'subject', 'school_class')},
            },
        ),
    ]
