# Generated by Django 5.0.6 on 2026-05-21 05:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('school_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Назва періоду')),
                ('kind', models.CharField(choices=[('term', 'Семестр'), ('quarter', 'Чверть'), ('year', 'Річна')], default='term', max_length=16, verbose_name='Тип')),
                ('start_date', models.DateField(verbose_name='Початок')),
                ('end_date', models.DateField(verbose_name='Кінець')),
                ('is_open', models.BooleanField(default=True, verbose_name='Відкритий для оцінювання')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_periods', to='school_core.academicyear')),
            ],
            options={
                'verbose_name': 'Період оцінювання',
                'verbose_name_plural': 'Періоди оцінювання',
                'ordering': ['academic_year', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(help_text='12-бальна шкала', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Бал')),
                ('kind', models.CharField(choices=[('current', 'Поточна'), ('control', 'Контрольна'), ('homework', 'Домашня'), ('oral', 'Усна відповідь'), ('final', 'Підсумкова')], default='current', max_length=16, verbose_name='Тип оцінки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='school_core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school_core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_given', to='accounts.teacherprofile')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='grades.gradeperiod')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'subject', 'date'], name='grades_grad_student_5b64a0_idx'), models.Index(fields=['teacher', 'date'], name='grades_grad_teacher_458d72_idx')],
            },
        ),
    ]
