# Generated by Django 5.0.6 on 2026-05-21 05:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Дата зарахування')),
                ('student_id', models.CharField(max_length=32, unique=True, verbose_name='Особова справа №')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
            options={
                'verbose_name': 'Профіль учня',
                'verbose_name_plural': 'Профілі учнів',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=32, unique=True, verbose_name='Табельний номер')),
                ('specialization', models.CharField(blank=True, max_length=120, verbose_name='Спеціалізація')),
                ('qualification_category', models.CharField(blank=True, help_text='Вища / Перша / Друга / Спеціаліст', max_length=64, verbose_name='Категорія')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='Дата прийняття')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
            ],
            options={
                'verbose_name': 'Профіль вчителя',
                'verbose_name_plural': 'Профілі вчителів',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('teacher', 'Вчитель'), ('student', 'Учень'), ('parent', 'Батьки')], default='student', max_length=16, verbose_name='Роль')),
                ('middle_name', models.CharField(blank=True, max_length=80, verbose_name='По батькові')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('mother', 'Мати'), ('father', 'Батько'), ('guardian', 'Опікун'), ('other', 'Інше')], default='other', max_length=16, verbose_name='Відношення')),
                ('workplace', models.CharField(blank=True, max_length=120, verbose_name='Місце роботи')),
                ('contact_preferences', models.JSONField(blank=True, default=dict, help_text='Канали (email, sms, in_app) та події', verbose_name='Налаштування сповіщень')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль батьків',
                'verbose_name_plural': 'Профілі батьків',
            },
        ),
    ]
