# Generated by Django 5.0.6 on 2026-05-21 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Тема')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат-сесія',
                'verbose_name_plural': 'Чат-сесії',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('assistant', 'Асистент'), ('system', 'Системне')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'verbose_name': 'Повідомлення чату',
                'verbose_name_plural': 'Повідомлення чату',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В обробці'), ('ready', 'Готово'), ('failed', 'Помилка')], default='pending', max_length=16, verbose_name='Статус')),
                ('risk_level', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('unknown', 'Невідомо')], default='unknown', max_length=16, verbose_name='Рівень ризику')),
                ('summary', models.TextField(blank=True, verbose_name='Короткий висновок')),
                ('strengths', models.TextField(blank=True, verbose_name='Сильні сторони')),
                ('concerns', models.TextField(blank=True, verbose_name='Зони уваги')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендації')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Сирі дані')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_insights', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'AI-аналіз учня',
                'verbose_name_plural': 'AI-аналізи учнів',
                'ordering': ['-created_at'],
            },
        ),
    ]
