# Generated by Django 5.0.6 on 2026-05-21 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('grade', 'Оцінка'), ('absence', 'Пропуск'), ('announcement', 'Оголошення'), ('ai_summary', 'AI-звіт'), ('system', 'Системне')], default='system', max_length=16, verbose_name='Тип')),
                ('channel', models.CharField(choices=[('in_app', 'У застосунку'), ('email', 'Email')], default='in_app', max_length=16, verbose_name='Канал')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('related_object_type', models.CharField(blank=True, max_length=40, verbose_name='Тип обʼєкту')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID обʼєкту')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Посилання')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Відправлено')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
