# Generated by Django 5.0.6 on 2026-05-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('school_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reason', models.CharField(choices=[('illness', 'Хвороба'), ('family', 'Сімейні обставини'), ('competition', 'Олімпіада/змагання'), ('unexcused', 'Без поважної причини'), ('other', 'Інше')], default='unexcused', max_length=16, verbose_name='Причина')),
                ('is_excused', models.BooleanField(default=False, verbose_name='Поважна')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('document', models.FileField(blank=True, null=True, upload_to='absences/', verbose_name='Довідка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='school_core.lesson')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_absences', to='accounts.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='school_core.subject')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуски',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', 'date'], name='attendance__student_b05f94_idx')],
            },
        ),
    ]
